import React from 'react';
import styles from './styles.module.css';

export const metadata = {
  title: "About page",
  description: "Generated by create next app",
};

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <nav>About navbar</nav>
      <main className={styles.main}>
        {children}
      </main>
    </>
  )
}
